vich_uploader:
    db_driver: orm

    mappings:
        event_document:
            uri_prefix: /uploads/events
            upload_destination: '%kernel.project_dir%/public/uploads/events'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
